# Generated by Django 6.0 on 2025-12-13 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locks', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LockPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lock_permissions', to='auth.group')),
                ('lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='locks.lock')),
                ('lock_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='locks.lock_group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lock_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'lock'], name='permissions_user_id_28a4c0_idx'), models.Index(fields=['user', 'lock_group'], name='permissions_user_id_7c14de_idx'), models.Index(fields=['group', 'lock'], name='permissions_group_i_eb0025_idx'), models.Index(fields=['group', 'lock_group'], name='permissions_group_i_925e7b_idx')],
                'unique_together': {('group', 'lock'), ('group', 'lock_group'), ('user', 'lock'), ('user', 'lock_group')},
            },
        ),
    ]
