# Generated by Django 6.0 on 2025-12-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lockpermission',
            unique_together=set(),
        ),
    ]
