# Generated by Django 6.0 on 2025-12-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('width', models.IntegerField(default=1000)),
                ('height', models.IntegerField(default=800)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schematics', to='schematics.building')),
            ],
        ),
        migrations.CreateModel(
            name='SchematicLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('scale_x', models.FloatField(default=1)),
                ('scale_y', models.FloatField(default=1)),
                ('rotation', models.FloatField(default=0)),
                ('color', models.CharField(default='black', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schematic_placements', to='locks.lock')),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schematic_locks', to='schematics.schematic')),
            ],
        ),
        migrations.CreateModel(
            name='SchematicWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('points', models.JSONField(default=list)),
                ('scale_x', models.FloatField(default=1)),
                ('scale_y', models.FloatField(default=1)),
                ('rotation', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='schematics.schematic')),
            ],
        ),
    ]
