# Generated by Django 6.0 on 2025-12-13 14:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id_lock', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('last_connexion', models.DateTimeField(blank=True, null=True)),
                ('is_reservable', models.BooleanField(default=False, help_text='Indique si cette serrure (salle) peut être réservée par les utilisateurs.')),
                ('auth_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('badge', 'Badge'), ('keypad', 'Keypad')], max_length=20), blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Lock_Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('locks', models.ManyToManyField(blank=True, related_name='groups', to='locks.lock')),
            ],
        ),
    ]
