# Generated by Django 6.0 on 2025-12-15 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockBatteryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locks.lock')),
            ],
        ),
    ]
