# Generated by Django 6.0 on 2025-12-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0002_lockbatterylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockbatterylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
