# Generated by Django 6.0 on 2025-12-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0003_alter_lockbatterylog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='remote_address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
