# Generated by Django 6.0 on 2025-12-13 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=16)),
                ('method', models.CharField(choices=[('keypad', 'Keypad'), ('badge', 'Badge')], max_length=10)),
                ('failed_code', models.CharField(blank=True, max_length=128, null=True)),
                ('lock_id', models.CharField(max_length=64)),
                ('lock_name', models.CharField(blank=True, max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
